### ISSUE TITLE
[Examples/Face Recognition] The results are incorrect with 'Tiny Yolo v2 Face(TFlite)'

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1226]
**Test Env:**
Chromium Version: nightly build  79.0.3917.0(d370896)
Platform:  all

**Expected Result:**
Examples should work.

**Actual Result:**
The results are incorrect on WASM/WebGL with 'Tiny Yolo v2 Face(TFlite)':

- Tiny Yolo v2 Face(TFlite) + FaceNet(OpenVINO)
- Tiny Yolo v2 Face(TFlite) + Face Reidentification(OpenVINO)
![WASM](https://user-images.githubusercontent.com/20039821/80326944-041c5580-886d-11ea-8588-c0a27453c6c5.png)
![WebGL](https://user-images.githubusercontent.com/20039821/80326947-07174600-886d-11ea-8547-d5991aaacba6.png)
![WASM-2](https://user-images.githubusercontent.com/20039821/80327151-b522f000-886d-11ea-95c6-15bf65432b1d.png)
![WebGL-2](https://user-images.githubusercontent.com/20039821/80327155-b81de080-886d-11ea-8541-ab9525437e3c.png)

**Comment by RayDai2010** [comment]
Fixed by PR #1229, the results by WASM and WebGL are as following:

![ty-1](https://user-images.githubusercontent.com/64256644/80343456-7d7d6d80-8898-11ea-86f3-cf03ebb89097.JPG)

![ty-2](https://user-images.githubusercontent.com/64256644/80343465-8110f480-8898-11ea-8651-6f3b365a62ba.JPG)

![ty-21](https://user-images.githubusercontent.com/64256644/80345195-596f5b80-889b-11ea-8b76-1c6ae9d77824.JPG)
![ty-22](https://user-images.githubusercontent.com/64256644/80345202-5bd1b580-889b-11ea-9c8f-4072cd3a1826.JPG)

**Comment by BruceDai** [comment]
Fixed by PR #1229, the results by WASM and WebGL are as following:

![ty-1](https://user-images.githubusercontent.com/1531742/80345557-de5a7500-889b-11ea-9518-7dcc3c9a0fd0.JPG)

![ty-2](https://user-images.githubusercontent.com/1531742/80345550-db5f8480-889b-11ea-8802-85a3a91cced9.JPG)

![ty-21](https://user-images.githubusercontent.com/1531742/80345561-df8ba200-889b-11ea-9c6b-d73569a765c8.JPG)

![ty-22](https://user-images.githubusercontent.com/1531742/80345568-e0243880-889b-11ea-9250-057f20926840.JPG)

**Comment by Christywl** [comment]
This issue has been fixed on the latest codes https://github.com/intel/webml-polyfill/commit/b563f945e5122af30efa8e7be0887598886892c1.
