### ISSUE TITLE
[Example] SqueezeNet and PoseNet fail on Chromium WebML build

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#176]
They works on Chrome with webml-polyfill but fail on Chromium WebML build.

Console log
```
main.js:135 Uncaught (in promise) TypeError: Cannot read property '_backend' of undefined
    at utils.init.then.catch (main.js:135)
```

@BruceDai , please see whether it is related to PR #170.

**Comment by BruceDai** [comment]
@huningxin  This issue is not reproduced on Mac OS platform using MPS and BNNS backends and Android platform using NNAPI backend by latest chromium 41afa08.
I check it on Windows platform also by latest chromium 41afa08, on posenet this issue is not reproduced, while failed to test squeezenet example with error "DOMException: finishfails: 5" not same as above error.

**Comment by huningxin** [comment]
@BruceDai Thanks for your effort! It looks like a Windows specific issue. Please file another issue for that and close this one. I can help verify.

**Comment by Christywl** [comment]
Filed #183 for Windows issue, and close this.
