### ISSUE TITLE
[example] Support to switch preference options for example.

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#196]
Currently we use url parameter prefer=fast or prefer=sustained to switch BNNS or MPS backend, and the test html page would relaunch.

**Comment by Wenzhao-Xiang** [comment]
I have pushed the demo on my github.io, please help take a look!
https://wenzhao-xiang.github.io/intel/webml-polyfill/
@ibelem @pinzhenx

**Comment by pinzhenx** [comment]
I saw there are calls to `getPreferfromSwitch()` in `ImageClassificationModel.js`, `OnnxModelImporter.js`, etc.. It introduced dependency on frontend into the "importer", since `getPreferParamfromSwitch` will get the state from HTML elements.

I tend to pass the `preference` from the `init()` in `main.js`, then down to the constructor in `utils.js`.

The constructor may look like this:
```js
class ImageClassificationModel {
  constructor(tfModel, options) {       <---------
    this._tfModel = tfModel;
    this._model = null;
    this._compilation;
    this._execution;
    this._tensorIds = [];
    this._operandIndex = 0;
    this._options = options || {};      <---------
    this._backend = this._options.backend;
    if (this._backend === 'WebML') {
      if (nnNative === null) {
        throw Error('Fails to initialize neural network context');
      }
      this._nn = nnNative;
    } else if (this._backend === 'WASM' || this._backend === 'WebGL2') {
      this._nn = nnPolyfill;
    }
  }

  async createCompiledModel() {
    this._model =
      await this._nn.createModel({ backend: this._backend });

    this._addTensorOperands();
    this._addOpsAndParams();
    this._addInputsOutputs()

    await this._model.finish();
    this._compilation = await this._model.createCompilation();

    let prefer = this._options.prefer || nn.PREFER_FAST_SINGLE_ANSWER;  <-----
    this._compilation.setPreference(prefer);                            <-----
    await this._compilation.finish();
    this._execution = await this._compilation.createExecution();
  }
```
 
Here I combine the model options and backend options into an object, the parameter `options` may look like this:
```js
options = {
  backend: 'WebML',
  prefer: nn.PREFER_SUSTAINED_SPEED,
  softmax: true,
}
```

**Comment by Wenzhao-Xiang** [comment]
Thanks, let's talk it in [PR-239](https://github.com/intel/webml-polyfill/pull/329).
