### ISSUE TITLE
[Linux] Missing libclDNN64.so on Linux

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#200]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**_313c1c2_**)
Device: Linux Ubuntu

**Expected Result:**
Chromium starts successfully.

**Actual Result:**
```
$ chromium-browser-unstable 
/usr/bin/chromium-browser-unstable: error while loading shared libraries: libclDNN64.so: cannot open shared object file: No such file or directory
```

**Comment by fujunwei** [comment]
Before workaround: 
1, Install opencl sdk
2, Copy libclDNN.so to chromium installed library

Use openvino following [standard document](https://software.intel.com/en-us/articles/OpenVINO-Install-Linux) now:
1, [Install openvino sdk](https://software.intel.com/en-us/articles/OpenVINO-Install-Linux#inpage-nav-3-2)  with `sudo ./install.sh`
2, [Set the Environment Variables ](https://software.intel.com/en-us/articles/OpenVINO-Install-Linux#inpage-nav-3-3)with `source /opt/intel/computer_vision_sdk/bin/setupvars.sh` in order to find libclDNN.so
3, [Install openCL  driver](https://software.intel.com/en-us/articles/OpenVINO-Install-Linux#inpage-nav-4-1) with `cd /opt/intel/computer_vision_sdk/install_dependencies/` && `./install_NEO_OCL_driver.sh
`
4, run chromium with shell command `/usr/bin/chromium-browser-unstable  --no-sandbox`

**Comment by fujunwei** [comment]
@BruceDai  please help to verify, thanks.

**Comment by Christywl** [comment]
Verified it with these steps, it worked.
