### ISSUE TITLE
[Sample] Add TinyYOLO based object detection example

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#29]

**Comment by huningxin** [comment]
https://github.com/ModelDepot/tfjs-yolo-tiny

**Comment by Wenzhao-Xiang** [comment]
Reference: 
https://github.com/experiencor/keras-yolo2
https://github.com/kaka-lin/object-detection

I Implement a simple Tiny-YoloV2 example.

image:
![image](https://user-images.githubusercontent.com/40754037/51157816-8a04cf00-18bc-11e9-895c-371a96edc2ab.png)

camera:
![image](https://user-images.githubusercontent.com/40754037/51157852-b6205000-18bc-11e9-9a2a-6e3850f442c0.png)

The model structure is similar to https://github.com/intel/webml-polyfill/issues/373#issuecomment-449962624, and have an output of [1, 13, 13, 425] with 80 coco classes.

And same to https://github.com/intel/webml-polyfill/issues/373#issuecomment-449962624, the new op we need is [Maximum](https://www.tensorflow.org/api_docs/python/tf/math/maximum)

Since this example have some difference in model init, I will next try to do code refactor for ssd_mobilenet and merge these two examples to object detection.
@huningxin

**Comment by ibelem** [comment]
Move to Feb 2019 milestone.
