### ISSUE TITLE
[Sample] Optimize TF.js PoseNet sample with WebML

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#55]
https://github.com/tensorflow/tfjs-models/tree/master/posenet

**Comment by halton** [comment]
Load/parse done, execution is ongoing.

**Comment by yl495** [comment]
Execution is done
https://github.com/yl495/webml-polyfill/tree/master/examples/posnet

**Comment by yl495** [comment]
dilation convolution:
https://github.com/intel/webml-polyfill/issues/79

**Comment by yl495** [comment]
After setting up a model, if I want to create another model in different parameter, WASM would throw an error.
`webml-polyfill.js:16782 Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 267649024, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 `

**Comment by ibelem** [comment]
Done, close it.
