### ISSUE TITLE
[Example] support big size model deployment on github.io

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#597]
The size of inception v4 and inception resnet v2 are bigger than 100MB. github.com refuses to host them. The potential solution might be splitting the big model file into multiple parts and assemble them by model loader.

@ibelem , any thoughts?

**Comment by ibelem** [comment]
Since this is not the issue of our code but the limitation of Github, I prefer to link the inception v4 and inception resnet v2 to CDN rather than update codes for them specificly unless there are performance improvements by assembling multiple parts with model loader. 

If you don't mind, the following links can be used in your site:

```
http://belem.oss-cn-shanghai.aliyuncs.com/webml/model/ic/inception_v3.tflite
http://belem.oss-cn-shanghai.aliyuncs.com/webml/model/ic/inception_v4.tflite 
```

There is other similar case below, currently we are using Google storage rather than local github.io and our webml-polyfill repo to store skeleton detection model (of course this model was splitted into multiple parts)

```
  const urlBase = 'https://storage.googleapis.com/tfjs-models/weights/posenet/';
  // const urlBase = '../skeleton_detection/model/';
```

**Comment by huningxin** [comment]
> of course this model was splitted into multiple parts

This is exactly that inspires me. :)



> If you don't mind, the following links can be used in your site:
> 
> ```
> http://belem.oss-cn-shanghai.aliyuncs.com/webml/model/ic/inception_v4.tflite   162.767MB
> http://belem.oss-cn-shanghai.aliyuncs.com/webml/model/ic/inception_resnet_v2.tflite   115.391MB
> ```

Thanks for offering this. I'd like to try.

**Comment by huningxin** [comment]
> https://belem.oss-cn-shanghai.aliyuncs.com/webml/model/ic/inception_v4.tflite   162.767MB
> https://belem.oss-cn-shanghai.aliyuncs.com/webml/model/ic/inception_resnet_v2.tflite   115.391MB

The CDN works and is deployed. Thanks!
