### ISSUE TITLE
[NNAPI] Support MAXIMUM op

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#631]

**Comment by mingmingtasd** [comment]
I find that this issue is caused by function "AddOperation" in "services/ml/model_impl_android.cc". In other words, the result returned by function "ANeuralNetworksModel_addOperation" is wrong. And the result type is "BAD_DATA". It's indicated by Android NDK that MAXIMUM is avaliable since API level 29 (Android version 10.0), so the low Android version may be the reason. I will try to test this issue on Android phone with version 10.0.

**Comment by mingmingtasd** [comment]
Finally, I found that the test cases for maximum had something wrong. After modifying the function “identifyInputsAndOutputs” in the test cases, this issue could be fixed.

**Comment by BruceDai** [comment]
@cuiyanx please fix this issue of maximum test , thanks

**Comment by BruceDai** [comment]
Fixed by PR #1016, close it.

**Comment by Christywl** [comment]
MAXIMUM op works on NNAPI(Android 10) with build https://github.com/otcshare/chromium-src/commit/270f639f9ab6be2eeeb86fb9ab82930cf94fb60a.
