### ISSUE TITLE
[BNNS] The outputs are incorrect for ADD and MUL operations

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#875]
**Test Env:**
Chromium Version: nightly build 75.0.3739.0 (f456c6d)
Platform: macOS

**Expected Result:**
The test should pass.

**Actual Result:**
The outputs are incorrect for ADD and MUL operations after #732 was fixed. 
<img width="1440" alt="Screen Shot 2019-06-26 at 9 41 48 AM" src="https://user-images.githubusercontent.com/20039821/60144903-d30b6880-97f6-11e9-99ed-f043e338d187.png">

**How to Reproduce:**
Visit https://brucedai.github.io/webnnt/test/issue-add-and-mul.html?prefer=fast

**Comment by huningxin** [comment]
@lisa0314 , could you please elaborate the root cause here? It would help review the fix. Thanks.

**Comment by lisa0314** [comment]
These two test cases set op1 as input instead of op0:
`model.addOperation(nn.ADD, [input0, input1, fusedActivationFuncNone], [output]);
model.identifyInputsAndOutputs([input1], [output]);`
I  saved the inputs values except  the input for model into `operation.extend_input` in the compilation process:
` operation.extend_input.push_back(input_memory)`

**Comment by huningxin** [comment]
@lisa0314 , thanks for the explanation. Your solution sounds good.

**Comment by Christywl** [comment]
This issue was fixed with https://github.com/otcshare/chromium-src/commit/775b7014eff6866bcad4921d61b41ac0d1c98d54.
