### ISSUE TITLE
[NNAPI] Support ARGMAX op

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#948]

**Comment by mingmingtasd** [comment]
Perhaps, this issue's reason is the same as that of issue #631, plz get details from the comment under issue #631.

**Comment by mingmingtasd** [comment]
ARGMAX test results:
https://brucedai.github.io/webnnt/test/argmax.html?prefer=sustained
Android: all pass

Manual regression test results:
https://brucedai.github.io/webnnt/test/index-local.html?prefer=sustained
Android 10.0: passes: 431 failures: 286 ([baseline](https://github.com/intel/webml-polyfill/blob/master/test/tools/RegressionChecker/baseline/baseline.config.json#L30): "pass": 435, "fail": 282) (four more fails of DEPTHWISE_CONV_2D caused by Android version 10.0)
Android 9.0: passes: 435 failures: 282 ([baseline](https://github.com/intel/webml-polyfill/blob/master/test/tools/RegressionChecker/baseline/baseline.config.json#L30): "pass": 435, "fail": 282)

Now ARGMAX can be supported on Android 10.0.

**Comment by mingmingtasd** [comment]
ARGMAX has been supported on Android 10 now.

**Comment by Christywl** [comment]
ARGMAX works on NNAPI(Android 10) with https://github.com/otcshare/chromium-src/commit/def95eb6c61c0eeb40f654873d6faeb98e1ca66c. It's not supported on Android 9.
